// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGXW8lMGs2guVUmRyNW6GyYfOWA8nsduU',
    appId: '1:904387613070:web:fa66626e86353e25d614df',
    messagingSenderId: '904387613070',
    projectId: 'flame-49dfd',
    authDomain: 'flame-49dfd.firebaseapp.com',
    databaseURL: 'https://flame-49dfd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flame-49dfd.appspot.com',
    measurementId: 'G-FW599QXJPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBplFIACpp3-G46bdF5gOF3YqBIn9st1gA',
    appId: '1:904387613070:android:e8ec956e4f2d6150d614df',
    messagingSenderId: '904387613070',
    projectId: 'flame-49dfd',
    databaseURL: 'https://flame-49dfd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flame-49dfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTfu2emMsxfBqiDcam4GSIJCKRmL9bidw',
    appId: '1:904387613070:ios:71e1076ad1843ef6d614df',
    messagingSenderId: '904387613070',
    projectId: 'flame-49dfd',
    databaseURL: 'https://flame-49dfd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flame-49dfd.appspot.com',
    iosClientId: '904387613070-gj70qnrs5a52qbq9040o6gj1vd0qp9tm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTfu2emMsxfBqiDcam4GSIJCKRmL9bidw',
    appId: '1:904387613070:ios:71e1076ad1843ef6d614df',
    messagingSenderId: '904387613070',
    projectId: 'flame-49dfd',
    databaseURL: 'https://flame-49dfd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flame-49dfd.appspot.com',
    iosClientId: '904387613070-gj70qnrs5a52qbq9040o6gj1vd0qp9tm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flame',
  );
}
